/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package petsimulator;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 *
 * @author Lisa Petrov, modifications by AJ
 */
//Responsible for displaying game graphics 
public class GraphicsHandler {
    
    //Displays the real world time and how the apple tree is doing
    public void displayTime(TimeSystem time, AppleTree tree) {
        System.out.println();
        System.out.println("=============================================================");
        System.out.printf("  %-30s Apple tree: %d/%d%n",
                time.getRealTimeText(), tree.getApples(), AppleTree.MAX_APPLES);
        if (!tree.isFull()) {
            System.out.printf("  Next apple in about %d min           Needs drop in %d min%n",
                    tree.minutesUntilNextApple(), time.minutesUntilNextDrop());
        }
        System.out.println("=============================================================");
    }

    //Displays pet stats and pet image 
    //Method generated with claude
    public void displayPet(Pet pet) {
        System.out.println("\n");
        PetNeeds needs = pet.getNeeds();
        System.out.printf("Pet: %3s  (age %d day(s))%n", pet.getName(), pet.getAge());
        System.out.printf("Energy: %3d/100          Hunger: %3d/100          Happiness: %3d/100%n",
                needs.getEnergy(), needs.getHunger(), needs.getHappiness());

        System.out.println();
        System.out.println("             /\\       /\\");
        System.out.println("            /   \\   /   \\");
        System.out.println("           /     \\_/     \\");
        System.out.println("          /    O      O   \\");
        System.out.println("         |         v       |");
        System.out.println("          \\      ----     /");
        System.out.println("           \\_____________/");
        System.out.println();
    }

    //method generated by claude
    //Displays player's inventory
    public void displayInventory(Inventory inventory, Class<? extends Item> type) {
        ArrayList<Item> items = inventory.getItems();
        
        LinkedHashMap<String, Integer> counts = new LinkedHashMap<>();
        for (Item item : items) {
            if (type.isInstance(item)) {
                counts.merge(item.getName(), 1, Integer::sum);
            }
        }

        ArrayList<String> labels = new ArrayList<>();
        for (Map.Entry<String, Integer> entry : counts.entrySet()) {
            labels.add(entry.getKey() + " x" + entry.getValue());
        }

        System.out.println("Inventory:");
        for (int i = 0; i < labels.size(); i += 3) {
            StringBuilder row = new StringBuilder();
            for (int col = 0; col < 3; col++) {
                int index = i + col;
                if (index < labels.size()) {
                    row.append(String.format("%-20s", labels.get(index)));
                }
            }
            System.out.println(row.toString());
        }
        System.out.println();
    }
}
